from enum import StrEnum


class MachineState(StrEnum):
    DISCONNECTED = "DISCONNECTED"
    CONNECTED = "CONNECTED"
    ALARM = "ALARM"
    HOMING = "HOMING"
    READY = "READY"
    MOVING_TO_MEDICINE = "MOVING_TO_MEDICINE"
    Z_DOWN_PICK = "Z_DOWN_PICK"
    Z_UP_PICK = "Z_UP_PICK"
    MOVING_TO_DESTINATION = "MOVING_TO_DESTINATION"
    Z_DOWN_DROP = "Z_DOWN_DROP"
    Z_UP_DROP = "Z_UP_DROP"
    RETURNING_HOME = "RETURNING_HOME"
    DONE = "DONE"
    ERROR = "ERROR"
    STOPPED = "STOPPED"

